%*******Plot a 2D chart for the number of bankruptcies due to credit shocks**********
close all;
discount=linspace(0,2,100);
subplot(2,2,1);
plot(discount,round_1_data);
grid on;
title('Round One');
xlabel("discount rate");
ylabel("Num of banks in distress");
set(gca,'xtick',0:0.4:2);
subplot(2,2,2);
plot(discount,round_2_data);
grid on;
title('Round Two');
xlabel("discount rate");
ylabel("Num of banks in distress");
set(gca,'xtick',0:0.4:2);
subplot(2,2,3);
plot(discount,round_3_data);
grid on;
title('Round Three');
xlabel("discount rate");
ylabel("Num of banks in distress");
set(gca,'xtick',0:0.4:2);
subplot(2,2,4);
plot(discount,round_4_data);
grid on;
title('Round Four');
xlabel("discount rate");
ylabel("Num of banks in distress");
set(gca,'xtick',0:0.4:2);

%*******Plot a 2D chart for asset impairment due to liquidity shocks**********
close all;
load('decreaseL.mat');
discount=linspace(0,2,100);
subplot(2,2,1);
plot(discount,decrease1);
grid on;
title('Round One');
xlabel("discount rate");
ylabel("Loss of bank equity");
set(gca,'xtick',0:0.4:2);
subplot(2,2,2);
plot(discount,decrease2);
grid on;
title('Round Two');
xlabel("discount rate");
ylabel("Loss of bank equity");
set(gca,'xtick',0:0.4:2);
subplot(2,2,3);
plot(discount,decrease3);
grid on;
title('Round Three');
xlabel("discount rate");
ylabel("Loss of bank equity");
set(gca,'xtick',0:0.4:2);
subplot(2,2,4);
plot(discount,decrease4);
grid on;
title('Round Four');
xlabel("discount rate");
ylabel("Loss of bank equity");
set(gca,'xtick',0:0.4:2);

%*******Plot a 2D chart for the number of bankruptcies due to credit shocks**********
close all;
%M=80;
delta=linspace(0,1,M);
subplot(2,2,1);
plot(delta,round_1_data);
grid on;
title('Round One');
set(gca,'xtick',0:0.2:1);
xlabel("default loss rate");
ylabel("Num of banks in distress");
subplot(2,2,2);
plot(delta,round_2_data);
grid on;
title('Round Two');
set(gca,'xtick',0:0.2:1);
xlabel("default loss rate");
ylabel("Num of banks in distress");
subplot(2,2,3);
plot(delta,round_3_data);
grid on;
title('Round Three');
set(gca,'xtick',0:0.2:1);
xlabel("default loss rate");
ylabel("Num of banks in distress");
subplot(2,2,4);
plot(delta,round_4_data);
grid on;
title('Round Four');
set(gca,'xtick',0:0.2:1);
xlabel("default loss rate");
ylabel("Num of banks in distress");

% ***********Plot a 2D chart for asset impairment due to credit shocks***********
close all;
load('AA2.mat');
delta=linspace(0,1,M);
subplot(2,2,1);
plot(delta,decrease_1_data);
grid on;
title('Round One');
xlabel("default loss rate");
ylabel("Loss of bank equity");
set(gca,'xtick',0:0.2:1);
subplot(2,2,2);
plot(delta,decrease_2_data);
grid on;
title('Round Two');
xlabel("default loss rate");
ylabel("Loss of bank equity");
set(gca,'xtick',0:0.2:1);
subplot(2,2,3);
plot(delta,decrease_3_data);
grid on;
title('Round Three');
xlabel("default loss rate");
ylabel("Loss of bank equity");
set(gca,'xtick',0:0.2:1);
subplot(2,2,4);
plot(delta,decrease_4_data);
grid on;
title('Round Four');
xlabel("default loss rate");
ylabel("Loss of bank equity"); 
set(gca,'xtick',0:0.2:1);

% Plot a 3D chart for the number of bankruptcies due to both credit and liquidity shocks
clear;close all;
delta=linspace(0,1,50);
discount=linspace(0,2,50);
load('AA1_0.2.mat');
Seq=41;
round1=round_1_data(Seq,:);
round2=round_2_data(Seq,:);
round3=round_3_data(Seq,:);
round4=round_4_data(Seq,:);
s=discount(Seq)*ones(1,50);
subplot(2,2,1);
surf(delta,discount,round_1_data);
set(gca,'ZLim',[0 200]);
colormap(jet);
% hold on
% plot3(delta,s,round1,'color',[0.86,0.86,0.86],'linewidth',3);
title('Round One');
xlabel("default loss rate");
ylabel("discount rate");
zlabel("Num of banks in distress");
% axis([1 20 0 1]);
% xlabel("bank num");
% ylabel("delta");
% axis([1 20 0 1]);
subplot(2,2,2);
surf(delta,discount,round_2_data);
% hold on
% plot3(delta,s,round2,'color',[0.86,0.86,0.86],'linewidth',3);
title('Round Two');
xlabel("default loss rate");
ylabel("discount rate");
zlabel("Num of banks in distress");
% % axis([1 20 0 1]);
% % bar3(AA1_data,0.5);
subplot(2,2,3);
surf(delta,discount,round_3_data);
% hold on
% plot3(delta,s,round3,'color',[0.86,0.86,0.86],'linewidth',3);
title('Round Three');
xlabel("default loss rate");
ylabel("discount rate");
zlabel("Num of banks in distress");
% % axis([1 20 0 1]);
subplot(2,2,4);
surf(delta,discount,round_4_data);
% hold on
% plot3(delta,s,round4,'color',[0.86,0.86,0.86],'linewidth',3);
title('Round Four');
xlabel("default loss rate");
ylabel("discount rate");
zlabel("Num of banks in distress");
% axis([1 20 0 1]);

% Plot a 3D chart for asset impairment due to both credit and liquidity shocks
close all;
load('decreaseXL.mat');
M=50;
N=50;
decrease1=decrease1(1:M,1:M);
decrease2=decrease2(1:M,1:M);
decrease3=decrease3(1:M,1:M);
decrease4=decrease4(1:M,1:M);
discount=linspace(0,2,M);
delta=linspace(0,1,N);
Seq=41;
decrease_1=decrease1(Seq,:);
decrease_2=decrease2(Seq,:);
decrease_3=decrease3(Seq,:);
decrease_4=decrease4(Seq,:);
save('decreaseerwei','decrease_1','decrease_2','decrease_3','decrease_4')
s=discount(Seq)*ones(1,50);
subplot(2,2,1);
mesh(delta,discount,decrease1);
% hold on
% plot3(delta,s,decrease_1,'color','r','linewidth',1.5);
% set(gca,'ZLim',[0 200]);
colormap(jet);

title('Round One');
xlabel("default loss rate");
ylabel("discount rate");
zlabel("Loss of bank equity");
set(gca,'xtick',0:0.2:1);
subplot(2,2,2);
mesh(delta,discount,decrease2);
% hold on
% plot3(delta,s,decrease_2,'color','r','linewidth',1.5);
title('Round Two');
xlabel("default loss rate");
ylabel("discount rate");
zlabel("Loss of bank equity");
set(gca,'xtick',0:0.2:1);
subplot(2,2,3);
mesh(delta,discount,decrease3);
% hold on
% plot3(delta,s,decrease_3,'color','r','linewidth',1.5);
title('Round Three');
xlabel("default loss rate");
ylabel("discount rate");
zlabel("Loss of bank equity");
set(gca,'xtick',0:0.2:1);
subplot(2,2,4);
mesh(delta,discount,decrease4);
% hold on
% plot3(delta,s,decrease_4,'color','r','linewidth',1.5);
title('Round Four');
xlabel("default loss rate");
ylabel("discount rate");
zlabel("Loss of bank equity");
set(gca,'xtick',0:0.2:1);
